import type { Config } from 'tailwindcss'

export default {
  // 显式扫描 app/，避免 JIT 漏掉类名
  content: ['./app/**/*.{vue,js,ts,mjs}'],
  corePlugins: {
    // 关闭 Preflight 后，浏览器对 p / a / button 等的默认样式会保留得多一些
    // preflight: false,
  },
  darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-background": "#f1f3fc",
              "primary-dim": "#9392ff",
              "secondary": "#a790fe",
              "secondary-fixed-dim": "#c9baff",
              "inverse-primary": "#4f4dcd",
              "tertiary-container": "#fd8bcc",
              "surface": "#0a0e14",
              "background": "#0a0e14",
              "tertiary-fixed": "#fd8bcc",
              "secondary-fixed": "#d7caff",
              "surface-container-lowest": "#000000",
              "on-tertiary": "#6e1150",
              "secondary-dim": "#a58dfb",
              "on-primary-container": "#10007f",
              "on-surface": "#f1f3fc",
              "secondary-container": "#4c329c",
              "surface-tint": "#a5a5ff",
              "on-tertiary-fixed-variant": "#6c104f",
              "outline-variant": "#44484f",
              "on-secondary-container": "#d6c9ff",
              "primary-fixed-dim": "#8686ff",
              "surface-bright": "#262c36",
              "tertiary-fixed-dim": "#ed7ebe",
              "on-secondary-fixed-variant": "#563da6",
              "surface-dim": "#0a0e14",
              "on-primary-fixed": "#000000",
              "on-secondary": "#260073",
              "on-tertiary-container": "#610246",
              "on-error-container": "#ffb2b9",
              "primary-fixed": "#9695ff",
              "surface-container-highest": "#20262f",
              "outline": "#72757d",
              "inverse-surface": "#f8f9ff",
              "surface-container": "#151a21",
              "surface-variant": "#20262f",
              "on-secondary-fixed": "#391b89",
              "error-dim": "#d73357",
              "error": "#ff6e84",
              "surface-container-high": "#1b2028",
              "error-container": "#a70138",
              "on-tertiary-fixed": "#350025",
              "surface-container-low": "#0f141a",
              "inverse-on-surface": "#51555c",
              "on-primary": "#19059d",
              "on-surface-variant": "#a8abb3",
              "tertiary-dim": "#ed7ebe",
              "on-error": "#490013",
              "primary": "#a5a5ff",
              "on-primary-fixed-variant": "#16009a",
              "primary-container": "#9695ff",
              "tertiary": "#ffa1d4",
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Plus Jakarta Sans"],
              "label": ["Plus Jakarta Sans"]
            },
            borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
          },
        },
} satisfies Config
